filetype indent on
syntax enable

set tabstop=4
set shiftwidth=4
set noexpandtab
set autoindent
set number
set hlsearch
set ignorecase
set encoding=utf-8
set fileencoding=utf-8
set wrap
set laststatus=2

